- title: A Detailed Comparative Analysis of Blockchain Consensus Mechanisms
  authors:
    - Kaeli Andrews
    - Linh B. Ngo
    - Md Amiruzzaman
  publisher: 41st CCSC Eastern Regional Conference
  date: 2025-10-25
  link: TBD
  tags:
    - blockchain

- title: Evaluating the Limitations of Local LLMs in Solving Complex Programming Challenges
  authors:
    - Kadin Matotek 
    - Heather Cassel
    - Md Amiruzzaman
    - Linh B. Ngo
  publisher: 41st CCSC Eastern Regional Conference
  date: 2025-10-25
  link: https://arxiv.org/abs/2509.15283
  tags:
    - best-paper
    - large-language-models

- title: One YAML File to Describe Them All
  authors:
    - Linh B. Ngo 
    - Huy Nguyen
    - Bao Ngo 
    - Tejas Karusala
  publisher: 41st CCSC Eastern Regional Conference
  date: 2025-10-25
  link: TBD
  tags:
    - computer-science-education
    - containerization